#!/usr/bin/env bash
# A bash script that displays information about subdomains

display_info()
{
	script=$(dig "$2"."$1" +noall +answer)
        echo "$2 $script" | awk '{print "The subdomain "$1" is a "$5" record and points to "$6}'
}

if [[ "$#" -eq 1 ]]
then
 display_info "$1" "www"
 display_info "$1" "lb-01"
 display_info "$1" "web-01"
 display_info "$1" "web-02"
fi

if [[ "$#" -eq 2 ]]
then
 display_info "$1" "$2"
fi
