#!/usr/bin/env bash
# A bash script that displays information about subdomains

display_info()
{
	script=$(dig "$2"."$1" +noall +answer | tr '\t' '\n' | tail -2 | tr '\n' ' ')
        echo "$2 $script" | awk '{print "The subdomain "$1" is a "$2" record and points to "$3}'
}

if [[ "$#" == 1 ]]
then
 display_info "$1" "www"
 display_info "$1" "lb-01"
 display_info "$1" "web-01"
 display_info "$1" "web-02"
elif [[ "$#" == 2 ]]
then
 display_info "$1" "$2"
fi
