#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server

if [[ $# -lt 3 ]]
then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

if [[ $# -lt 4 ]]; then
  scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
  exit 0
fi

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

echo "${IP}"
echo "${PATH_TO_FILE}"
echo "${USERNAME}"
echo "${PATH_TO_SSH_KEY}"
scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
