#!/usr/bin/env bash
# Install nginx web server
# Requirements:
#	 Install nginx on your web-01 server
#        Nginx should be listening on port 80
#	 When querying Nginx at its root / with a GET request (requesting a page) using curl, 
#	 It must return a page that contains the string Hello World!

sudo apt-get update -y && sudo apt-get upgrade -y

sudo apt-get install nginx -y

sudo echo "Hello World!" > /var/www/html/index.html

sudo ufw allow "Nginx HTTP"

sudo service nginx start

sudo service nginx status
