#!/usr/bin/env bash
# Install nginx web server
apt-get update && sudo apt-get upgrade -y

apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.html

ufw allow 'Nginx HTTP'

service nginx start

service nginx status
