#!/usr/bin/env bash
# A script that configures your Nginx server so that /redirect_me is redirecting to another page
apt update && apt upgrade -y
apt install nginx -y
echo "Hello World!" > /var/www/html/index.html
STRING_TO_REPLACE="server_name _;\n\tlocation =\/redirect_me {\n\t\treturn 301 'https://www.youtube.com/watch?v=QH2-TGUlwu4';\n\t}"
sed -i "s/server_name _;/${STRING_TO_REPLACE}/" /etc/nginx/sites-enabled/default
service nginx start
