#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
apt update && apt upgrade -y
apt install nginx -y
echo "Hello World!" > /var/www/html/index.html
STRING_TO_REPLACE="server_name _;\n\trewrite ^\/redirect_me 'https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4' permanent;"
sed -i "s/server_name _;/${STRING_TO_REPLACE}/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page." > /var/www/html/404.html

STR="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation =\/404.html {\n\t\tinternal;\n\t}"
sed -i "s/listen 80 default_server;/${STR}/" /etc/nginx/sites-enabled/default
nginx -t && service nginx start
