#!/usr/bin/env bash
# This script reacts to the SIGTERM signal

trap 'echo "I hate the kill command"' SIGTERM

trap 'echo "Y U no love me?!"' SIGINT

trap 'rm /var/run/myscript.pid ; exit' SIGQUIT SIGTERM

while true
do
    echo "To infinity and beyond"
    
    sleep 2
done
