#!/usr/bin/env bash
# This script prints Best School X10 conditionally

i=1

while [[ $i -lt 11 ]]
do

    if [[ $i -eq 9 ]]
    then
        echo -e "Best School\nHi"

    else
        echo "Best School"
    fi

    ((i++))
done
