#!/usr/bin/env bash
# This script prints 1-20 conditionally

i=1

while [[ $i -lt 21 ]]
do

    case  $i in

     4)
        echo -e "${i}\nbad luck from China"
	;;

     9)
        echo -e   "${i}\nbad luck from Japan"
	;;

     17)
        echo -e "${i}\nbad luck from Italy"
	;;

     *)
        echo "$i"
	;;
    esac

    ((i++))
done
