#!/usr/bin/env bash
# Bash script that configures an Ubuntu server
# Requirements:
#      localhost resolves to 127.0.0.2
#      facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new

sed -i 's/127.0.0.1\tlocalhost$//' ~/hosts.new

sed -i 's/157.240.11.35\tfacebook.com$//' ~/hosts.new

echo -e "127.0.0.2\tlocalhost" >> ~/hosts.new

echo -e "8.8.8.8\tfacebook.com" >> ~/hosts.new

cp -f ~/hosts.new /etc/hosts
