#!/usr/bin/env bash
# Bash script that configures an Ubuntu server
# Requirements:
#      localhost resolves to 127.0.0.2
#      facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new

sed -i 's/127\.0\.0\.1/127\.0\.0\.2/g' ~/hosts.new

sed -i 's/157\.240\.11\.35/8\.8\.8\.8/' ~/hosts.new

cp -f ~/hosts.new /etc/hosts
