#!/usr/bin/env bash
# A script that makes the solution to task 1 shorter and sweet

sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx start
